### ISSUE TITLE
FileLink?

### ISSUE THREAD

**Issue by Calvyn82** [gedankenstuecke/snpr#200]
I'm looking through the models for low-hanging fruit on unit tests or refactoring and I came across FileLink.

https://github.com/gedankenstuecke/snpr/search?utf8=%E2%9C%93&q=filelink

What exactly is this doing, and what are the two controllers doing with it? I'm not seeing it show up in the views anywhere. Is some gem or something using it and I'm not seeing where?

**Comment by philippbayer** [comment]
IMO this is old overhang - we used to display the link to the zip-file of all genotypings using this one, since it returns 

    #<ActiveRecord::Relation [#<FileLink id: 1, description: "all genotypes and phenotypes archive", url: "/data/zip/opensnp_datadump.201406061816.zip", created_at: "2011-12-13 01:13:54", updated_at: "2014-06-06 20:47:08">]>

That way, we always had a link to the newest genotyping zip in the database. But this is now handled by `Zipfulldata.public_path`. 

I think FileLink can go from the looks of it? The controller itself is unchanged from 2013, the genotypes controller lines even go back to 2012

**Comment by Calvyn82** [comment]
If you want me to, I'll strip out the model and the parts of the controller that assign it to an instance variable. I'll wait for your go-ahead to do so.

**Comment by philippbayer** [comment]
I think we can kick these out, do the tests etc. still work then? I'd assume so

**Comment by Calvyn82** [comment]
The tests still work fine. As far as I can tell, it won't change a thing.

**Comment by philippbayer** [comment]
Merged, thank you very much for your help :)
